# Generated by Django 3.2.7 on 2022-10-08 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history_images/')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('custom_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('original_work', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Written as YYYY-MM-DD')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, help_text='Written as YYYY-MM-DD', null=True)),
                ('active', models.BooleanField(default=True)),
                ('custom_display_name', models.CharField(blank=True, help_text='Leave blank if you want your name to show up', max_length=200, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('laugh_score', models.PositiveBigIntegerField(default=0)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='history.image')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
