# Generated by Django 3.2.7 on 2022-10-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyevent',
            old_name='image',
            new_name='cover_image',
        ),
    ]
