# Generated by Django 3.2.7 on 2022-10-10 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_rename_image_historyevent_cover_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='HistoryImage',
        ),
    ]
